### ISSUE TITLE
Warning triggered using sprintf 

### ISSUE THREAD

**Issue by oyvble** [jverzani/gWidgets2#105]
Using newer releases of R (4.1.0 or newer):

Warning is triggered at:
https://github.com/jverzani/gWidgets2/blob/b103f520653cf40cadccd05f549bd2c981852dce/R/guiToolkit.R#L108

name = "tcltk"
sprintf("gWidgets2%s", name, sep="")

**Comment by ggrothendieck** [comment]
In R 4.0.3. the `sprintf` statement in question does not result in a warning but it does in R 4.1.  

Also the output of the `require` on the same line is not checked. Is it intended that it keep processing if the require fails?

**Comment by jverzani** [comment]
I guess I need to fix this. Will try next week.

**Comment by jverzani** [comment]
Sorry this took so long to address. A fix is here https://github.com/gwidgets3/gWidgets2/pull/1 and has been submitted to CRAN
