### ISSUE TITLE
Gtk-CRITICAL **: gtk_tree_view_unref_tree_helper: assertion 'node != NULL' failed

### ISSUE THREAD

**Issue by landroni** [jverzani/gWidgets2#11]
https://github.com/landroni/gWidgets2-filter/blob/master/gWidgets2-filter.R
I always get this message. No idea if this is important: 
(R:11669): Gtk-CRITICAL **: gtk_tree_view_unref_tree_helper: assertion `node != NULL' failed

**Comment by OskarHansson** [comment]
> I found an easy way to reproduce this error:
> 
> ```
> w <- gwindow()
> d <- gdf(mtcars, cont=w)
> ```
> 
> Closing the window will yield:
> 
> ```
> (R:26259): Gtk-CRITICAL **: gtk_tree_view_unref_tree_helper: assertion 'node != NULL' failed
> ```
> 
> Is there a way to fix this error message? In dffilter I'm now using two gdf() instances, and the error message can pollute the console for the user.

Thanks @landroni! I got this error my package, without any reference to where it occurred in the code. Your example saved me much time pinpointing the error. @jverzani answer also made me confident ignoring the error.
