### ISSUE TITLE
Setting height and width in ggraphics() doesn't work

### ISSUE THREAD

**Issue by davidcsterratt** [jverzani/gWidgets2#83]
`ggraphics()` seems to behave differently in gWidgets2 from the gWidgets, as illustrated below
```
## Expect two grpahics areas side by-side, each 500x500 pixels
library(gWidgets)                       # Works
## library(gWidgets2)                   # Doesn't work; areas are smaller (default size?)
options(guiToolkit="RGtk2")

h <- function(h, ...) {}

g.win <- gwindow("Test ggraphics()")
g.body <- ggroup(container=g.win)
g.fd1 <- ggraphics(width=500, height=500, ps=11, container=g.body)
g.fd2 <- ggraphics(width=500, height=500, ps=11, container=g.body)
```

**Comment by jverzani** [comment]
Thanks for the report! Most appreciated.

 For some reason I had commented out the code for setting the size in ggraphics.R from gWidgets2RGtk2. I pushed a fix, hopefully it doesn't break something else. You can install that with devtools, or use the `size<-` method.

**Comment by davidcsterratt** [comment]
Great - that seems to have done the trick. I'll let you know if it transpires that something is broken.
