### ISSUE TITLE
Is handler argument of gfile() really deprecated?

### ISSUE THREAD

**Issue by davidcsterratt** [jverzani/gWidgets2#86]
Before using some `addHandler()` code, I was just checking that the `handler` argument of `gfile()` really is deprecated: 
```
gWidgets2::gfile("Hello", handler=function(h, ...) {print("hello")})
Argument handler has been deprecated:
	 o 
```
Fine if it is!

**Comment by jverzani** [comment]
I made `gfile` modal and `gfilebrowse` non-modal (so it could have a handler). The modal one seemed to be easier for people to use.

**Comment by davidcsterratt** [comment]
Thanks - makes sense now! As far as I can see, my Retistruct package is now fully working with gWidgets2.
