### ISSUE TITLE
addSpace

### ISSUE THREAD

**Issue by gregu4** [jverzani/gWidgets2#87]
Hi,
seems to me it doesn't work.
the following does'nt add 200px between frames.
Am I mistaken ?
thx
options(guiToolkit="RGtk2")

library("gWidgets2RGtk2")

g=gwindow()
gr=ggroup(cont=g)
gf=gframe("testzzzzzz",cont=gr)
addSpace(gr,200)
gframe("test",cont=gr)

**Comment by jverzani** [comment]
Wow, sorry I took so long to see this. Thanks for filing the report. This is fixed with the most recent check in to gWidgets2RGtk2.
